### ISSUE TITLE
Plugin causes high CPU load

### ISSUE THREAD

**Issue by rahra** [TwoCanPlugIn/ActisensePlugin#1]
The plugin causes opencpn to run at 100% CPU load.
I tested this on the latest Debian (bookworm/sid) as well as on Ubuntu 20.04.4 LTS (focal fossa).
The plugin basically works, but causes very high CPU load on both systems.

I compiled the Actisense library from this repo.
Any hint where this could come from?

**Comment by TwoCanPlugIn** [comment]
Hi Bernhard,

No work has been done on this for a few years.

In response to a request from a few users a while ago to support the Actisense NGT-1, I forked a very early version of the TwoCan plugin and figured out what the Actisense bits should be.

It never really saw the light of day as I personally do not have a NGT-1 to test, and was reliant on others.

I have no idea what would be causing the high CPU load. Just having a quick peruse, I see that is scattered with heaps of things that were never implemented (I was thinking of some SignalK stuff at the time) and also that there is a lot of wxMessageOutputDebug().Printf  debug spew.

Perhaps go through the code and comment out all of the debug crud. One question, do you also see high loads if using EBL log files ? That may narrow down the culprit. Also, the Linux serial port code may be far from optimal !

My suggestion if you want to use your NGT-1 with a proven & reliable solution, would be to use SignalK in conjunction with canboat, rather than persevere with this Actisense plugin. I'm sorry that I don't have the time nor inclination to do any more work on it.

Regards.


________________________________
From: Bernhard R. Fischer ***@***.***>
Sent: 09 May 2022 10:05
To: TwoCanPlugIn/ActisensePlugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TwoCanPlugIn/ActisensePlugin] Plugin causes high CPU load (Issue #1)


The plugin causes opencpn to run at 100% CPU load.
I tested this on the latest Debian (bookworm/sid) as well as on Ubuntu 20.04.4 LTS (focal fossa).
The plugin basically works, but causes very high CPU load on both systems.

I compiled the Actisense library from this repo.
Any hint where this could come from?

**Comment by rahra** [comment]
Thanks for your reply!
I already started commenting out things ;) probably I find the somewhere.
And I already stumbled on canboat. I'll give it a try.
Otherwise I'll switch to another N2K bus device, since this must work realiably for me.

Best regards,
Berrnhard

**Comment by TwoCanPlugIn** [comment]
Hi Bernhard,

Have fun playing around with my Actisense code base. Unfortunately (and I think I describe this on the readme), because of the nuances of the NGT-1, it lacks some of the features of the TwoCan plugin, which is now is several releases further along, with a number of bug fixes and additional features.

As an alternative to the NGT-1, there are a couple of ways you can go. If you just want a "black" box connection between the N2K bus and anything else (not just OpenCPN but any software that consumes NMEA 0183), any of the commercial gateways (Actisense NGW, Shipmodul, Yacht Devices) work well.

If you are a hobbyist and want to tinker on Linux with an USB connected adapter,  then any adapter that supports the SocketCAN interface will work. Depending on your budget, there are several adapters that do this; Canable Cantact, Rusoku Toucan, Kvaser, Peak Systems,  and many more.

If you are using a Raspberry PI, in addition to USB connected adapters there are also many CAN Hats that connect directly to the Pi's motherboard.

The SocketCAN adapters are supported by my TwoCan plugin for direct integration with OpenCPN and are supported by Canboat and consequently SignalK for integration with both OpenCPN and SignalK enabled displays.

Good luck.


________________________________

**Comment by rahra** [comment]
Hi!

Thanks for your response. I already went with Canboat and SignalK some time ago which works like a charm.
No need for the plugin any more.

Best regards,
Bernhard

**Comment by TwoCanPlugIn** [comment]
Hi Bernhard,

Glad that you have a working solution that you are happy with. 
You may also be interested in the next release of OpenCPN which will have basic NMEA 2000 support built-in and does support the Actisense NGT-1.
The alpha release of v5.7 was announced on the forum: https://www.cruisersforum.com/forums/f134/opencpn-version-5-7-alpha-test-268872.html
Kind regards.
