### ISSUE TITLE
PGN 127508 Current is signed, and (debatable) so is voltage

### ISSUE THREAD

**Issue by ieb** [TwoCanPlugIn/ActisensePlugin#2]
https://github.com/TwoCanPlugIn/ActisensePlugin/blob/953afc1eb506da464ec46f7eff9db7665fb29ee1/src/actisense_device.cpp#L1468C3-L1468C17

There might be a bug here. Current can be both +ve and -ve. All the doc I can find on PGN127508 indicates that current is a signed  field not unsigned. According to the code references about, batteries monitored by TwoCanPlugin can only charge or discharge, and but not both (fortunately not the case ;) ).

There is also debate  about the voltage field which some say is signed and other say unsigned. (https://github.com/ttlappalainen/NMEA2000/issues/321 vs CanBoat)  PGN 127489 has voltages (Alternator Voltage) as signed.... but then signed battery voltage only makes sense if a battery is connected in reverse.

I guess this is the consequences of having proprietary standards that no one can read without buying them..... they become broken standards.

**Comment by TwoCanPlugIn** [comment]
This plugin is no longer in use/maintained etc.

The NMEA 2000 decoding routines that were used in this plugin were those that were originally used in early versions of the TwoCan plugin.

I'll check and update the handling of PGN 1274898 in TwoCan. My assumption is that Timo's libraries should be correct, however from the sample data I have, the routines in TwoCan seem to make sense.

Regarding current, really need to have some sample data from a NMEA 2000 equipped battery monitor whilst the batteries are being charged, rather than discharged and compare the NMEA 2000 data with what is show on the battery monitor display.
